"use client";
import { useEffect, useState, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Cta from "@/components/Cta";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import MoreInfoModal from "@/components/MoreInfoModal";
import MoreInfo from "@/components/MoreInfoModal";
import Navbar from "@/components/Navbar";
import Student from "@/components/Student";
import Teacher from "@/components/Teachers";
import Values from "@/components/Values";
import { BsArrowUp } from "react-icons/bs";
import { useSpring, animated } from "react-spring";

export default function Home() {
  const [isVisible, setIsVisible] = useState(false);

  // Show button when page is scorlled upto given distance
  const toggleVisibility = () => {
    if (window.pageYOffset > 300) {
      setIsVisible(true);
    } else {
      setIsVisible(false);
    }
  };

  // Set the top cordinate to 0
  // make scrolling smooth
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  useEffect(() => {
    window.addEventListener("scroll", toggleVisibility);
    return () => window.removeEventListener("scroll", toggleVisibility);
  }, []);

  const springProps = useSpring({
    loop: { reverse: true },
    to: { scale: isVisible ? 1.2 : 1 },
    from: { scale: 1 },
    config: { tension: 200, friction: 20 },
  });

  return (
    <div>
      <Head>
        <title>Ed -Circle Education Website</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Values />
      <Teacher />
      <Student />
      <MoreInfoModal />
      <Cta />
      <Footer />

      {isVisible && (
        <animated.button
          onClick={scrollToTop}
          className="fixed bottom-20 right-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-2 rounded-full flex items-center justify-center"
          style={springProps}
        >
          <BsArrowUp size={24} />
        </animated.button>
      )}
    </div>
  );
}
