"use client";
import Head from "next/head";
import Image from "next/image";
import Cta from "@/components/Cta";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import MoreInfoModal from "@/components/MoreInfoModal";
import MoreInfo from "@/components/MoreInfoModal";
import Navbar from "@/components/Navbar";
import Student from "@/components/Student";
import Teacher from "@/components/Teachers";
import Values from "@/components/Values";
import { useEffect, useState } from "react";

export default function Home() {
  const [isVisible, setIsVisible] = useState(false);

  // Show button when page is scorlled upto given distance
  const toggleVisibility = () => {
    if (window.pageYOffset > 300) {
      setIsVisible(true);
    } else {
      setIsVisible(false);
    }
  };

  // Set the top cordinate to 0
  // make scrolling smooth
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  useEffect(() => {
    window.addEventListener("scroll", toggleVisibility);
    return () => window.removeEventListener("scroll", toggleVisibility);
  }, []);

  return (
    <div>
      <Head>
        <title>Ed -Circle Education Website</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Values />
      <Teacher />
      <Student />
      <MoreInfoModal />
      <Cta />
      <Footer />
    </div>
  );
}

// {isVisible && (
//   <button
//     onClick={scrollToTop}
//     className="fixed bottom-2 right-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
//   >
//     Go to Top
//   </button>
// )}
